# Generated by Django 5.0.3 on 2024-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0003_movie_actors_movie_director_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='main_picture',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='director',
            name='main_picture',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_picture',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
